{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "prometheusDS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "# Нормальные запросы\nsum(increase(http_requests_total{status!=\"429\",path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "Ok Requests"
    },
    {
     "expr": "sum(increase(http_requests_total{status=\"429\",path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "429 Requests"
    }
   ]
  },
  {
   "title": "Request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{path!=\"/metrics\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RateLimitErr ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{status=\"429\",path!=\"/metrics\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RateLimitErr rate per request",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status=~\"429\",path!=\"/metrics\"}[$__rate_interval])) \n/ \nsum(rate(http_requests_total{path!=\"/metrics\"}[$__rate_interval])) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}