# Build stage
FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main ./server/cmd/main.go

# Run stage
FROM alpine:3.18
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=builder /app/main ./main
COPY ./server/sample-cfg.yaml ./sample-cfg.yaml
EXPOSE 8080
CMD ["./main", "--config=sample-cfg.yaml"]